In [15]:
import numpy as np
import pandas as pd

In [16]:
df=pd.read_csv("C:/Users/HRUSHIKESH/OneDrive/Desktop/DSBDA/dataset_Facebook.csv",sep=";")

In [17]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [18]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [7]:
df.dtypes

Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions    object
dtype: object

In [19]:
df.shape

(500, 19)

In [20]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Page total likes                                                     500 non-null    int64
 1   Type                                                                 500 non-null    object
 2   Category                                                             500 non-null    int64
 3   Post Month                                                           500 non-null    int64
 4   Post Weekday                                                         500 non-null    int64
 5   Post Hour                                                            500 non-null    int64
 6   Paid                                                                 499 non-null    float64
 7   Lifetime Post Total Reach                                            500 non-null    int64
 8   Lifetime Post Total Impressions                                      500 non-null    int64
 9   Lifetime Engaged Users                                               500 non-null    int64
 10  Lifetime Post Consumers                                              500 non-null    int64
 11  Lifetime Post Consumptions                                           500 non-null    int64
 12  Lifetime Post Impressions by people who have liked your Page         500 non-null    int64
 13  Lifetime Post reach by people who like your Page                     500 non-null    int64
 14  Lifetime People who have liked your Page and engaged with your post  500 non-null    int64
 15  comment                                                              500 non-null    int64
 16  like                                                                 499 non-null    float64
 17  share                                                                496 non-null    float64
 18  Total Interactions                                                   500 non-null    int64
dtypes: float64(3), int64(15), object(1)
memory usage: 74.3+ KB

In [22]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [23]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [10]:
df.dtypes

Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions    object
dtype: object

In [24]:
df["Paid"]=df["Paid"].fillna(df["Paid"].mean())

In [25]:
df["like"]=df["like"].fillna(df["like"].mean())
df["share"]=df["share"].fillna(df["share"].mean())

In [26]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   0
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   0
share                                                                  0
Total Interactions                                                     0
dtype: int64

In [27]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.000000,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.000000,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.000000,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.000000,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.000000,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.000000,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.000000,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.000000,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.000000,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,0.278557,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [29]:
s1=df[df["Type"]=="Status"]
s1

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
38,138895,Status,2,12,7,9,0.0,17576,33058,5352,5202,6547,23135,11792,4104,11,227.0,31.0,269
40,138895,Status,2,12,6,11,0.0,13280,24198,2055,1912,2720,17627,9344,1716,7,216.0,39.0,262
46,138353,Status,1,12,3,11,0.0,16576,30612,3572,3464,4802,24363,12888,3014,4,174.0,36.0,214
72,137893,Status,3,11,4,11,0.0,9056,16362,1006,847,1153,9562,5180,740,3,226.0,44.0,273
80,137177,Status,2,11,7,3,0.0,8728,17827,2295,2235,2828,15418,7344,2099,2,86.0,13.0,101
84,137177,Status,3,11,5,2,0.0,6692,13092,199,108,141,7549,3336,156,2,99.0,16.0,117
98,137020,Status,2,10,5,3,1.0,12468,24917,2143,1966,2576,15850,7636,1661,7,310.0,61.0,378
107,136736,Status,2,10,1,4,0.0,9504,19556,1132,1032,1512,16018,7616,981,17,193.0,28.0,238
109,136736,Status,2,10,7,3,0.0,13872,27468,2664,2570,3395,20198,10432,2252,4,217.0,50.0,271
121,136393,Status,2,10,7,9,0.0,15816,30514,2733,2654,3289,23584,11912,2361,6,186.0,40.0,232
138,136013,Status,2,10,5,3,0.0,8896,17202,1480,1426,1932,13838,7020,1292,0,129.0,25.0,154
141,136013,Status,3,10,3,10,0.0,13152,25666,2543,2438,3179,20547,10280,2278,2,227.0,36.0,265
142,136013,Status,2,10,3,2,1.0,31136,59964,6164,5934,9237,35977,18048,4376,60,859.0,90.0,1009
148,135713,Status,2,10,7,4,0.0,10744,20691,1967,1877,2201,17502,8964,1834,3,148.0,28.0,179
163,135617,Status,2,9,6,4,0.0,11096,21080,1843,1724,2106,16095,8120,1604,4,243.0,41.0,288
172,135195,Status,2,9,1,10,0.0,21256,41906,4840,4754,5906,35455,17592,4318,38,163.0,27.0,228
175,135195,Status,2,9,6,10,1.0,13216,24738,2675,2584,2969,19599,10232,2342,2,165.0,22.0,189
180,134879,Status,2,9,4,4,1.0,9124,17776,1476,1397,1797,13887,7092,1331,20,150.0,29.0,199
202,132817,Status,2,8,3,2,1.0,9236,16054,1151,1130,1560,14014,7880,1075,2,53.0,15.0,70
217,131956,Status,2,8,2,12,0.0,14424,26000,304,286,383,25539,14056,291,41,15.0,1.0,57
222,131808,Status,2,8,7,4,0.0,8260,14305,997,953,1211,12905,7360,956,1,74.0,11.0,86
223,131808,Status,2,8,6,10,1.0,20168,35904,3370,3244,5106,26881,15056,2806,18,332.0,54.0,404
225,131808,Status,2,7,5,14,0.0,15296,25269,2827,2781,3627,22103,13296,2602,9,95.0,17.0,121
232,131630,Status,2,7,2,6,1.0,10824,20573,135,126,153,20030,10384,126,6,14.0,1.0,21
235,131300,Status,2,7,7,10,0.0,10956,19279,128,119,130,18838,10564,123,3,13.0,1.0,17
242,130791,Status,2,7,4,6,0.0,17360,33613,2573,2448,6017,23338,11800,1905,9,484.0,79.0,572
253,129600,Status,2,7,5,12,1.0,15576,27513,2417,2327,3098,19078,10840,1839,11,238.0,51.0,300
267,128032,Status,2,7,5,10,0.0,10188,16978,1473,1441,2136,14450,8536,1395,13,61.0,13.0,87
275,126424,Status,2,7,3,13,0.0,18320,31448,3742,3682,7854,25584,14920,3300,36,98.0,14.0,148
282,126345,Status,2,6,7,11,0.0,12044,20327,2240,2193,3599,17717,10400,2119,0,104.0,13.0,117
285,126141,Status,2,6,6,4,0.0,8628,14847,870,843,1692,11970,6796,774,4,72.0,18.0,94
334,119198,Status,2,5,1,2,0.0,10152,17099,1636,1599,2755,15382,8980,1613,2,55.0,10.0,67
352,116435,Status,1,5,4,3,1.0,23832,42313,1701,1570,2838,37816,21352,1578,6,210.0,39.0,255
362,116091,Status,2,5,5,7,0.0,9232,16811,908,861,1967,12996,7200,843,1,129.0,36.0,166
371,113028,Status,2,4,6,3,1.0,17912,34774,2750,2567,6591,21009,11408,2256,17,447.0,123.0,587
416,104070,Status,1,3,3,15,0.0,9120,14759,951,937,1290,13246,8004,924,3,25.0,6.0,34

In [30]:
s2=df[(df["Type"]=="Photo")& (df["Post Month"]>10)]
s2

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,137059,Photo,1,11,2,3,0.0,24720,37240,845,564,850,14475,8120,504,13,331.0,77.0,421
91,137059,Photo,2,11,1,9,0.0,2219,4545,287,220,329,3189,1495,221,0,78.0,13.0,91
92,137059,Photo,3,11,1,3,0.0,4732,9303,607,352,518,6201,3136,445,9,301.0,32.0,342
93,137059,Photo,3,11,7,9,0.0,2225,4239,310,216,289,2570,1389,233,2,111.0,16.0,129
94,137059,Photo,2,11,7,4,0.0,2626,4943,316,213,299,3047,1605,244,2,124.0,22.0,148

In [31]:
s3=df[df["Category"]==2]
s3

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.000000,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.000000,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
3,139441,Photo,2,12,2,10,1.000000,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.000000,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.000000,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467,91758,Photo,2,2,5,3,1.000000,15880,51571,1188,1071,1410,47976,13560,677,1,200.0,37.0,238
480,86909,Photo,2,1,4,11,0.000000,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
483,86491,Photo,2,1,3,3,0.000000,5526,8779,1096,1058,1399,5732,3412,453,2,69.0,26.0,97
496,81370,Photo,2,1,5,8,0.000000,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
499,81370,Photo,2,1,4,4,0.278557,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [32]:
s4=df[(df["Lifetime Post Consumptions"]>1000)& (df["Lifetime Engaged Users"]>860)]
s4

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,85979,Photo,3,1,7,10,0.0,9700,17442,1407,1271,2007,8872,4876,660,21,277.0,80.0,378
489,85979,Photo,3,1,7,2,0.0,4800,7754,975,938,1278,4932,2820,432,1,74.0,28.0,103
490,85979,Photo,3,1,6,11,0.0,5280,8703,951,911,1237,5757,3300,431,1,79.0,30.0,110
491,85979,Photo,3,1,6,3,1.0,6184,10228,956,901,1140,6085,3502,437,1,105.0,46.0,152
493,85093,Photo,3,1,1,2,0.0,8412,13960,1179,1111,1632,8632,5348,699,17,185.0,55.0,257

In [33]:
s5=df.iloc[:7,:6]
s5

   Page total likes    Type  Category  Post Month  Post Weekday  Post Hour
0            139441   Photo         2          12             4          3
1            139441  Status         2          12             3         10
2            139441   Photo         3          12             3          3
3            139441   Photo         2          12             2         10
4            139441   Photo         2          12             2          3
5            139441  Status         2          12             1          9
6            139441   Photo         3          12             1          3

In [34]:
s6=df[(df["Page total likes"]>13500)& (df["Lifetime Engaged Users"]>860)]
s6

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,85979,Photo,3,1,7,10,0.0,9700,17442,1407,1271,2007,8872,4876,660,21,277.0,80.0,378
489,85979,Photo,3,1,7,2,0.0,4800,7754,975,938,1278,4932,2820,432,1,74.0,28.0,103
490,85979,Photo,3,1,6,11,0.0,5280,8703,951,911,1237,5757,3300,431,1,79.0,30.0,110
491,85979,Photo,3,1,6,3,1.0,6184,10228,956,901,1140,6085,3502,437,1,105.0,46.0,152
493,85093,Photo,3,1,1,2,0.0,8412,13960,1179,1111,1632,8632,5348,699,17,185.0,55.0,257

In [35]:
s7=df[4:13]
s7

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104

In [36]:
s8=df.iloc[:4,:4]

s8

   Page total likes    Type  Category  Post Month
0            139441   Photo         2          12
1            139441  Status         2          12
2            139441   Photo         3          12
3            139441   Photo         2          12

In [37]:
s9=df.iloc[:4,3:14]
s9

,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page
0,12,4,3,0.0,2752,5091,178,109,159,3078,1640
1,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112
2,12,3,3,0.0,2413,4373,177,113,154,2812,1503
3,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048

In [38]:
Trans=df.transpose()
Trans

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.278557
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [64]:
merged_df1 = pd.concat([s2, s3], ignore_index=True)
merged_df1

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.000000,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Photo,3,12,3,3,0.000000,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
2,139441,Photo,2,12,2,10,1.000000,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
3,139441,Photo,2,12,2,3,0.000000,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
4,139441,Photo,3,12,1,3,1.000000,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,91758,Photo,2,2,5,3,1.000000,15880,51571,1188,1071,1410,47976,13560,677,1,200.0,37.0,238
195,86909,Photo,2,1,4,11,0.000000,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
196,86491,Photo,2,1,3,3,0.000000,5526,8779,1096,1058,1399,5732,3412,453,2,69.0,26.0,97
197,81370,Photo,2,1,5,8,0.000000,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
198,81370,Photo,2,1,4,4,0.278557,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [39]:
df_merged = pd.merge(s8, s9, how='inner')
df_merged

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640
1,139441,Photo,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112
2,139441,Photo,2,12,3,3,0.0,2413,4373,177,113,154,2812,1503
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048
4,139441,Status,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640
5,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112
6,139441,Status,2,12,3,3,0.0,2413,4373,177,113,154,2812,1503
7,139441,Status,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048
8,139441,Photo,3,12,4,3,0.0,2752,5091,178,109,159,3078,1640
9,139441,Photo,3,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112
10,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503
11,139441,Photo,3,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048
12,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640
13,139441,Photo,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112
14,139441,Photo,2,12,3,3,0.0,2413,4373,177,113,154,2812,1503
15,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048

In [40]:
merge=s8.merge(s9)
merge

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640
1,139441,Photo,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112
2,139441,Photo,2,12,3,3,0.0,2413,4373,177,113,154,2812,1503
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048
4,139441,Status,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640
5,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112
6,139441,Status,2,12,3,3,0.0,2413,4373,177,113,154,2812,1503
7,139441,Status,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048
8,139441,Photo,3,12,4,3,0.0,2752,5091,178,109,159,3078,1640
9,139441,Photo,3,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112
10,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503
11,139441,Photo,3,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048
12,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640
13,139441,Photo,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112
14,139441,Photo,2,12,3,3,0.0,2413,4373,177,113,154,2812,1503
15,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048

In [42]:
pivot_df = df.pivot_table(
    index="Post Month",
    columns="Type",
    values="Total Interactions",
    aggfunc="mean"
)

In [43]:
pivot_df

Type              Link       Photo      Status       Video
Post Month
1            66.250000  178.571429         NaN         NaN
2           131.000000  246.480000         NaN         NaN
3            46.666667  103.750000   34.000000         NaN
4           173.333333  212.369565  587.000000         NaN
5            63.000000  270.666667  162.666667         NaN
6                  NaN  157.521739  105.500000  271.000000
7                  NaN  350.159091  180.857143  409.000000
8                  NaN  234.866667  154.250000         NaN
9                  NaN  279.032258  226.000000  472.000000
10           95.000000  162.510204  340.750000         NaN
11          163.000000  183.157895  163.666667  248.333333
12           65.333333  227.677419  203.583333  174.000000

In [44]:
X = df.drop("Total Interactions", axis=1)
y = df["Total Interactions"]

# Keep only numeric
X = X.select_dtypes(include=np.number)

# Convert
X = X.values
y = y.values.reshape(-1,1)

print(X.shape, y.shape)

(500, 17) (500, 1)

In [46]:
df_sorted_likes = df.sort_values(
    by="like",
    ascending=False
)

(df_sorted_likes.head())

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
379,111620,Photo,3,4,1,14,1.0,105632,147918,3984,2254,3391,48575,27328,1936,51,1998.0,128.0,2177
349,117764,Photo,3,5,5,13,0.0,81856,124753,3000,1637,2718,52477,27392,1756,45,1639.0,122.0,1806
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777