In [39]:
import numpy as np
import pandas as pd

In [40]:
df=pd.read_csv("CAR.csv")
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000.0,100000.0,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000.0,46000.0,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000.0,141000.0,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000.0,83000.0,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000.0,90000.0,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000.0,40000.0,Petrol,Individual,Manual,First Owner

In [41]:
df.shape

(4340, 8)

In [42]:
df.describe()

              year  selling_price      km_driven
count  4340.000000   4.339000e+03    4338.000000
mean   2013.090783   5.042205e+05   66243.652374
std       4.215344   5.785829e+05   46636.666295
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.100000e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [43]:
df.isnull().sum()

name             0
year             0
selling_price    1
km_driven        2
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [44]:
df['km_driven']=df['km_driven'].fillna(df['km_driven'].mean())
df.isnull().sum()

name             0
year             0
selling_price    1
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [45]:
df=df.dropna()

In [46]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [47]:
df.shape

(4339, 8)

In [48]:
df.dtypes

name              object
year               int64
selling_price    float64
km_driven        float64
fuel              object
seller_type       object
transmission      object
owner             object
dtype: object

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4339 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4339 non-null   object
 1   year           4339 non-null   int64
 2   selling_price  4339 non-null   float64
 3   km_driven      4339 non-null   float64
 4   fuel           4339 non-null   object
 5   seller_type    4339 non-null   object
 6   transmission   4339 non-null   object
 7   owner          4339 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 305.1+ KB

In [50]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000.0,100000.0,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000.0,46000.0,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000.0,141000.0,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000.0,83000.0,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000.0,90000.0,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000.0,40000.0,Petrol,Individual,Manual,First Owner

In [51]:
df=df.drop('name',axis=1)
df

,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner
1,2007,135000.0,50000.0,Petrol,Individual,Manual,First Owner
2,2012,600000.0,100000.0,Diesel,Individual,Manual,First Owner
3,2017,250000.0,46000.0,Petrol,Individual,Manual,First Owner
4,2014,450000.0,141000.0,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...
4335,2014,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4336,2014,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4337,2009,110000.0,83000.0,Petrol,Individual,Manual,Second Owner
4338,2016,865000.0,90000.0,Diesel,Individual,Manual,First Owner
4339,2016,225000.0,40000.0,Petrol,Individual,Manual,First Owner

In [52]:
df = pd.get_dummies(df, drop_first=True)

In [53]:
df.corr(numeric_only=True)

,year,selling_price,km_driven,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
year,1.000000,0.413812,-0.419610,0.121137,-0.025551,-0.051303,-0.114609,-0.173558,0.100197,-0.143724,-0.186452,-0.292625,0.095797,-0.243526
selling_price,0.413812,1.000000,-0.192351,0.282835,-0.005097,-0.042448,-0.269336,-0.236727,0.110157,-0.530187,-0.078751,-0.162096,0.048792,-0.110916
km_driven,-0.419610,-0.192351,1.000000,0.285662,-0.001381,0.036628,-0.291394,0.181675,-0.089976,0.119550,0.097315,0.195719,-0.083512,0.194677
fuel_Diesel,0.121137,0.282835,0.285662,1.000000,-0.015068,-0.072447,-0.970927,-0.035187,-0.007947,-0.048027,-0.021088,0.003391,-0.010591,0.010223
fuel_Electric,-0.025551,-0.005097,-0.001381,-0.015068,1.000000,-0.001108,-0.014854,-0.026117,-0.002356,-0.044745,-0.002094,0.025959,-0.000952,-0.004160
fuel_LPG,-0.051303,-0.042448,0.036628,-0.072447,-0.001108,1.000000,-0.071419,0.035133,-0.011326,0.024770,0.013381,0.030132,-0.004578,0.004905
fuel_Petrol,-0.114609,-0.269336,-0.291394,-0.970927,-0.014854,-0.071419,1.000000,0.029713,0.012527,0.039540,0.011536,-0.012581,0.012444,-0.009376
seller_type_Individual,-0.173558,-0.236727,0.181675,-0.035187,-0.026117,0.035133,0.029713,1.000000,-0.266894,0.214129,0.072343,0.186666,-0.107882,0.140555
seller_type_Trustmark Dealer,0.100197,0.110157,-0.089976,-0.007947,-0.002356,-0.011326,0.012527,-0.266894,1.000000,-0.042335,-0.021400,-0.076788,-0.009731,-0.042512
transmission_Manual,-0.143724,-0.530187,0.119550,-0.048027,-0.044745,0.024770,0.039540,0.214129,-0.042335,1.000000,0.035608,0.068118,0.009157,0.030564
owner_Fourth & Above Owner,-0.186452,-0.078751,0.097315,-0.021088,-0.002094,0.013381,0.011536,0.072343,-0.021400,0.035608,1.000000,-0.080670,-0.008650,-0.037791
owner_Second Owner,-0.292625,-0.162096,0.195719,0.003391,0.025959,0.030132,-0.012581,0.186666,-0.076788,0.068118,-0.080670,1.000000,-0.036682,-0.160258
owner_Test Drive Car,0.095797,0.048792,-0.083512,-0.010591,-0.000952,-0.004578,0.012444,-0.107882,-0.009731,0.009157,-0.008650,-0.036682,1.000000,-0.017184
owner_Third Owner,-0.243526,-0.110916,0.194677,0.010223,-0.004160,0.004905,-0.009376,0.140555,-0.042512,0.030564,-0.037791,-0.160258,-0.017184,1.000000

In [54]:
df.corr()

,year,selling_price,km_driven,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
year,1.000000,0.413812,-0.419610,0.121137,-0.025551,-0.051303,-0.114609,-0.173558,0.100197,-0.143724,-0.186452,-0.292625,0.095797,-0.243526
selling_price,0.413812,1.000000,-0.192351,0.282835,-0.005097,-0.042448,-0.269336,-0.236727,0.110157,-0.530187,-0.078751,-0.162096,0.048792,-0.110916
km_driven,-0.419610,-0.192351,1.000000,0.285662,-0.001381,0.036628,-0.291394,0.181675,-0.089976,0.119550,0.097315,0.195719,-0.083512,0.194677
fuel_Diesel,0.121137,0.282835,0.285662,1.000000,-0.015068,-0.072447,-0.970927,-0.035187,-0.007947,-0.048027,-0.021088,0.003391,-0.010591,0.010223
fuel_Electric,-0.025551,-0.005097,-0.001381,-0.015068,1.000000,-0.001108,-0.014854,-0.026117,-0.002356,-0.044745,-0.002094,0.025959,-0.000952,-0.004160
fuel_LPG,-0.051303,-0.042448,0.036628,-0.072447,-0.001108,1.000000,-0.071419,0.035133,-0.011326,0.024770,0.013381,0.030132,-0.004578,0.004905
fuel_Petrol,-0.114609,-0.269336,-0.291394,-0.970927,-0.014854,-0.071419,1.000000,0.029713,0.012527,0.039540,0.011536,-0.012581,0.012444,-0.009376
seller_type_Individual,-0.173558,-0.236727,0.181675,-0.035187,-0.026117,0.035133,0.029713,1.000000,-0.266894,0.214129,0.072343,0.186666,-0.107882,0.140555
seller_type_Trustmark Dealer,0.100197,0.110157,-0.089976,-0.007947,-0.002356,-0.011326,0.012527,-0.266894,1.000000,-0.042335,-0.021400,-0.076788,-0.009731,-0.042512
transmission_Manual,-0.143724,-0.530187,0.119550,-0.048027,-0.044745,0.024770,0.039540,0.214129,-0.042335,1.000000,0.035608,0.068118,0.009157,0.030564
owner_Fourth & Above Owner,-0.186452,-0.078751,0.097315,-0.021088,-0.002094,0.013381,0.011536,0.072343,-0.021400,0.035608,1.000000,-0.080670,-0.008650,-0.037791
owner_Second Owner,-0.292625,-0.162096,0.195719,0.003391,0.025959,0.030132,-0.012581,0.186666,-0.076788,0.068118,-0.080670,1.000000,-0.036682,-0.160258
owner_Test Drive Car,0.095797,0.048792,-0.083512,-0.010591,-0.000952,-0.004578,0.012444,-0.107882,-0.009731,0.009157,-0.008650,-0.036682,1.000000,-0.017184
owner_Third Owner,-0.243526,-0.110916,0.194677,0.010223,-0.004160,0.004905,-0.009376,0.140555,-0.042512,0.030564,-0.037791,-0.160258,-0.017184,1.000000

In [56]:
x=df[["transmission_Manual"]]
y=df['selling_price']

In [57]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75)

In [58]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [59]:
reg.coef_

array([-1059157.50410864])

In [60]:
reg.intercept_

np.float64(1464011.5072046109)

In [63]:
y_pred=reg.predict(x_test)
y_pred

array([404854.00309598, 404854.00309598, 404854.00309598, ...,
       404854.00309598, 404854.00309598, 404854.00309598])

In [66]:
from sklearn.metrics import mean_squared_error,root_mean_squared_error,mean_absolute_error,r2_score
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

print(f"Mean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"R-squared: {r2}")
print(f"Root Mean Squared Error: {rmse}")

Mean Squared Error: 194116347155.76056
Mean Absolute Error: 280964.84013899264
R-squared: 0.21170551459543374
Root Mean Squared Error: 440586.36741932965

In [73]:
transmission = input("Enter transmission (Manual/Automatic): ")

if transmission.lower() == "manual":
    value = 1
elif transmission.lower() =="Automatic":
    value = 0
else:
    print("Invalid input. Please enter 'Manual' or 'Automatic'.")



prediction = reg.predict([[value]])

print("Predicted Selling Price:", prediction[0])

Enter transmission (Manual/Automatic): Manual
Predicted Selling Price: 404854.0030959754

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [74]:
x1=df.drop('selling_price',axis=1)
y1=df['selling_price']

In [75]:
from sklearn.model_selection import train_test_split
x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,train_size=0.7)

In [77]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x1_train,y1_train)

LinearRegression()

In [78]:
lr.coef_

array([ 3.36048008e+04, -1.00391933e+00,  2.93915016e+05, -5.71587599e+05,
        4.68084416e+04, -1.77523192e+04, -4.63213918e+04,  1.40479390e+05,
       -8.37624792e+05, -7.72017915e+03, -4.34743110e+04,  1.56498649e+05,
       -5.30177050e+04])

In [79]:
lr.intercept_

np.float64(-66423925.493271574)

In [80]:
y1_pred=lr.predict(x1_test)
y1_pred

array([136394.52393654, 139881.74492948, 203434.44250359, ...,
       542683.06225149, 728918.71693462, 448314.64552788])

In [81]:
from sklearn.metrics import mean_squared_error,root_mean_squared_error,mean_absolute_error,r2_score
mse=mean_squared_error(y1_test,y1_pred)
mae=mean_absolute_error(y1_test,y1_pred)
r2=r2_score(y1_test,y1_pred)
rmse=root_mean_squared_error(y1_test,y1_pred)

print(f"Mean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"R-squared: {r2}")
print(f"Root Mean Squared Error: {rmse}")

Mean Squared Error: 192484843913.35223
Mean Absolute Error: 225210.6969951291
R-squared: 0.4636688015069601
Root Mean Squared Error: 438730.9470659122

In [83]:
year = int(input("Enter year: "))
km = float(input("Enter km driven: "))

# initialize all dummy values as 0
fuel_Diesel = 0
fuel_Electric = 0
fuel_LPG = 0
fuel_Petrol = 0
seller_type_Individual = 0
seller_type_Trustmark_Dealer = 0
transmission_Manual = 0
owner_Second_Owner = 0
owner_Third_Owner = 0
owner_Fourth_Above_Owner = 0
owner_Test_Drive_Car = 0

# take category input
fuel = input("Fuel: ").lower()
if fuel == "diesel":
    fuel_Diesel = 1
elif fuel == "petrol":
    fuel_Petrol = 1

transmission = input("Transmission: ").lower()
if transmission == "manual":
    transmission_Manual = 1


user_data = [[
    year,
    km,
    fuel_Diesel,
    fuel_Electric,
    fuel_LPG,
    fuel_Petrol,
    seller_type_Individual,
    seller_type_Trustmark_Dealer,
    transmission_Manual,
    owner_Second_Owner,
    owner_Third_Owner,
    owner_Fourth_Above_Owner,
    owner_Test_Drive_Car
]]

prediction = lr.predict(user_data)
print("Predicted Price:", prediction[0])

Enter year: 2020
Enter km driven: 75000
Fuel: petrol
Transmission: manual
Predicted Price: 527101.0583606362

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(