In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv("C:\\Users\\Hp\\Downloads\\dataset_Facebook - dataset_Facebook.csv")
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [5]:
df.shape

(500, 19)

In [6]:
df.dtypes

Page total likes                                                         int64
Type                                                                    object
Category                                                                 int64
Post Month                                                               int64
Post Weekday                                                             int64
Post Hour                                                                int64
Paid                                                                   float64
Lifetime Post Total Reach                                                int64
Lifetime Post Total Impressions                                          int64
Lifetime Engaged Users                                                   int64
Lifetime Post Consumers                                                  int64
Lifetime Post Consumptions                                               int64
Lifetime Post Impressions by people who have liked your Page             int64
Lifetime Post reach by people who like your Page                         int64
Lifetime People who have liked your Page and engaged with your post      int64
comment                                                                  int64
like                                                                   float64
share                                                                  float64
Total Interactions                                                       int64
dtype: object

In [7]:
df.mean(numeric_only=True)

Page total likes                                                       123194.176000
Category                                                                    1.880000
Post Month                                                                  7.038000
Post Weekday                                                                4.150000
Post Hour                                                                   7.840000
Paid                                                                        0.278557
Lifetime Post Total Reach                                               13903.360000
Lifetime Post Total Impressions                                         29585.948000
Lifetime Engaged Users                                                    920.344000
Lifetime Post Consumers                                                   798.772000
Lifetime Post Consumptions                                               1415.130000
Lifetime Post Impressions by people who have liked your Page            16766.376000
Lifetime Post reach by people who like your Page                         6585.488000
Lifetime People who have liked your Page and engaged with your post       609.986000
comment                                                                     7.482000
like                                                                      177.945892
share                                                                      27.266129
Total Interactions                                                        212.120000
dtype: float64

In [8]:
df.median(numeric_only=True)

Page total likes                                                       129600.0
Category                                                                    2.0
Post Month                                                                  7.0
Post Weekday                                                                4.0
Post Hour                                                                   9.0
Paid                                                                        0.0
Lifetime Post Total Reach                                                5281.0
Lifetime Post Total Impressions                                          9051.0
Lifetime Engaged Users                                                    625.5
Lifetime Post Consumers                                                   551.5
Lifetime Post Consumptions                                                851.0
Lifetime Post Impressions by people who have liked your Page             6255.5
Lifetime Post reach by people who like your Page                         3417.0
Lifetime People who have liked your Page and engaged with your post       412.0
comment                                                                     3.0
like                                                                      101.0
share                                                                      19.0
Total Interactions                                                        123.5
dtype: float64

In [9]:
df.mode(numeric_only=True)

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,136393.0,1.0,10.0,7.0,3.0,0.0,677.0,4372.0,537.0,182.0,431.0,1210.0,690,403.0,0.0,98.0,13.0,0.0
1,NaN,NaN,NaN,NaN,NaN,NaN,2232.0,6503.0,NaN,298.0,513.0,1284.0,704,NaN,NaN,NaN,14.0,39.0
2,NaN,NaN,NaN,NaN,NaN,NaN,2645.0,7004.0,NaN,319.0,599.0,2541.0,1228,NaN,NaN,NaN,NaN,75.0
3,NaN,NaN,NaN,NaN,NaN,NaN,2938.0,8533.0,NaN,322.0,652.0,2888.0,1640,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,3322.0,8745.0,NaN,335.0,719.0,3675.0,1674,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,3358.0,12735.0,NaN,374.0,730.0,4911.0,1722,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,3414.0,NaN,NaN,482.0,795.0,4935.0,2044,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,3528.0,NaN,NaN,503.0,889.0,5010.0,2124,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,3754.0,NaN,NaN,513.0,NaN,5732.0,2162,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,5280.0,NaN,NaN,642.0,NaN,NaN,2174,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,5290.0,NaN,NaN,NaN,NaN,NaN,2388,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,6692.0,NaN,NaN,NaN,NaN,NaN,2426,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,9528.0,NaN,NaN,NaN,NaN,NaN,2604,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,13544.0,NaN,NaN,NaN,NaN,NaN,2616,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,32208.0,NaN,NaN,NaN,NaN,NaN,2644,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2660,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2704,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2752,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2868,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3114,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3216,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3230,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3298,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3768,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5348,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5372,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7020,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7800,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8032,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8120,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20608,NaN,NaN,NaN,NaN,NaN

In [10]:
df.mode(numeric_only=True).iloc[0]

Page total likes                                                       136393.0
Category                                                                    1.0
Post Month                                                                 10.0
Post Weekday                                                                7.0
Post Hour                                                                   3.0
Paid                                                                        0.0
Lifetime Post Total Reach                                                 677.0
Lifetime Post Total Impressions                                          4372.0
Lifetime Engaged Users                                                    537.0
Lifetime Post Consumers                                                   182.0
Lifetime Post Consumptions                                                431.0
Lifetime Post Impressions by people who have liked your Page             1210.0
Lifetime Post reach by people who like your Page                          690.0
Lifetime People who have liked your Page and engaged with your post       403.0
comment                                                                     0.0
like                                                                       98.0
share                                                                      13.0
Total Interactions                                                          0.0
Name: 0, dtype: float64

In [11]:
df.std(numeric_only=True)

Page total likes                                                       16272.813214
Category                                                                   0.852675
Post Month                                                                 3.307936
Post Weekday                                                               2.030701
Post Hour                                                                  4.368589
Paid                                                                       0.448739
Lifetime Post Total Reach                                              22740.787890
Lifetime Post Total Impressions                                        76803.246670
Lifetime Engaged Users                                                   985.016636
Lifetime Post Consumers                                                  882.505013
Lifetime Post Consumptions                                              2000.594118
Lifetime Post Impressions by people who have liked your Page           59791.023731
Lifetime Post reach by people who like your Page                        7682.009405
Lifetime People who have liked your Page and engaged with your post      612.725618
comment                                                                   21.180910
like                                                                     323.398742
share                                                                     42.613292
Total Interactions                                                       380.233118
dtype: float64

In [12]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [13]:
(df==0).sum()

Page total likes                                                         0
Type                                                                     0
Category                                                                 0
Post Month                                                               0
Post Weekday                                                             0
Post Hour                                                                0
Paid                                                                   360
Lifetime Post Total Reach                                                0
Lifetime Post Total Impressions                                          0
Lifetime Engaged Users                                                   0
Lifetime Post Consumers                                                  0
Lifetime Post Consumptions                                               0
Lifetime Post Impressions by people who have liked your Page             0
Lifetime Post reach by people who like your Page                         0
Lifetime People who have liked your Page and engaged with your post      0
comment                                                                106
like                                                                     5
share                                                                   13
Total Interactions                                                       6
dtype: int64

In [14]:
df.eq(0).sum()

Page total likes                                                         0
Type                                                                     0
Category                                                                 0
Post Month                                                               0
Post Weekday                                                             0
Post Hour                                                                0
Paid                                                                   360
Lifetime Post Total Reach                                                0
Lifetime Post Total Impressions                                          0
Lifetime Engaged Users                                                   0
Lifetime Post Consumers                                                  0
Lifetime Post Consumptions                                               0
Lifetime Post Impressions by people who have liked your Page             0
Lifetime Post reach by people who like your Page                         0
Lifetime People who have liked your Page and engaged with your post      0
comment                                                                106
like                                                                     5
share                                                                   13
Total Interactions                                                       6
dtype: int64

In [15]:
df.isna().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [16]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [17]:
df1=df.fillna(df.mode(numeric_only=True).iloc[0])
df1

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,0.0,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [18]:
df1.isna().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   0
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   0
share                                                                  0
Total Interactions                                                     0
dtype: int64

In [19]:
df1.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278000,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.786000,27.152000,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448462,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.094315,42.461215,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.750000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.250000,32.000000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [20]:
df2=df1[df1['like']>1000]
df2

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
101,137020,Photo,2,10,4,3,0.0,68896,104952,2624,1326,1952,35707,19840,1354,26,1505.0,95.0,1626
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
176,135195,Photo,3,9,6,3,1.0,22304,37159,1805,984,1618,22864,13304,1349,29,1047.0,98.0,1174
199,132817,Photo,3,8,4,10,0.0,33536,64850,1954,1016,1678,50076,24448,1564,33,1155.0,102.0,1290
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
323,123047,Photo,3,6,1,10,0.0,56672,104966,2579,1334,1850,78678,37408,1831,20,1372.0,47.0,1439
349,117764,Photo,3,5,5,13,0.0,81856,124753,3000,1637,2718,52477,27392,1756,45,1639.0,122.0,1806
379,111620,Photo,3,4,1,14,1.0,105632,147918,3984,2254,3391,48575,27328,1936,51,1998.0,128.0,2177
460,92507,Photo,3,2,1,13,0.0,55520,665792,4544,3586,6624,648611,47488,3430,146,1546.0,181.0,1873

In [21]:
df1['Type'].unique()

array(['Photo', 'Status', 'Link', 'Video'], dtype=object)

In [22]:
df1['Type']

0       Photo
1      Status
2       Photo
3       Photo
4       Photo
        ...
495     Photo
496     Photo
497     Photo
498     Photo
499     Photo
Name: Type, Length: 500, dtype: object

In [23]:
df3=df1[(df1['like']>5000)&(df1['share']>10)&(df1['comment']>50)]
df3

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334

In [24]:
df4=df1[(df1['Post Weekday']==7)&(df1['Post Hour']==5)]
df4

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
125,136393,Photo,1,10,7,5,0.0,677,1240,236,228,264,1098,580,196,0,7.0,2.0,9
448,96749,Photo,1,3,7,5,1.0,14320,21958,1850,1819,2170,9579,4664,413,2,59.0,6.0,67

In [25]:
df5=df1[(df1['Post Month']==5)&(df1['Post Weekday']==6)&(df1['Post Hour']>7)]
df5

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
336,119198,Photo,3,5,6,14,0.0,2772,4642,526,479,604,3353,1943,305,2,72.0,9.0,83
347,117764,Photo,3,5,6,13,0.0,3144,5067,392,356,507,3586,2148,271,1,58.0,13.0,72
348,117764,Photo,3,5,6,8,1.0,4336,7705,574,484,847,5156,2752,403,12,155.0,23.0,190
360,116091,Photo,1,5,6,9,0.0,6000,10300,577,539,886,7886,4454,429,3,72.0,24.0,99

In [26]:
df6=df1[df1['Lifetime People who have liked your Page and engaged with your post']>2500]
df6

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
38,138895,Status,2,12,7,9,0.0,17576,33058,5352,5202,6547,23135,11792,4104,11,227.0,31.0,269
46,138353,Status,1,12,3,11,0.0,16576,30612,3572,3464,4802,24363,12888,3014,4,174.0,36.0,214
142,136013,Status,2,10,3,2,1.0,31136,59964,6164,5934,9237,35977,18048,4376,60,859.0,90.0,1009
172,135195,Status,2,9,1,10,0.0,21256,41906,4840,4754,5906,35455,17592,4318,38,163.0,27.0,228
223,131808,Status,2,8,6,10,1.0,20168,35904,3370,3244,5106,26881,15056,2806,18,332.0,54.0,404
225,131808,Status,2,7,5,14,0.0,15296,25269,2827,2781,3627,22103,13296,2602,9,95.0,17.0,121
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
275,126424,Status,2,7,3,13,0.0,18320,31448,3742,3682,7854,25584,14920,3300,36,98.0,14.0,148
460,92507,Photo,3,2,1,13,0.0,55520,665792,4544,3586,6624,648611,47488,3430,146,1546.0,181.0,1873

In [27]:
df7=df1[(df1['Lifetime Post Impressions by people who have liked your Page']>100000)&(df1['Lifetime Post reach by people who like your Page']>5000)&(df1['Lifetime People who have liked your Page and engaged with your post']>500)]
df7

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
203,132817,Photo,3,8,2,10,0.0,72864,205934,946,759,1158,122474,30912,646,4,220.0,19.0,243
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
277,126424,Video,1,6,2,13,0.0,139008,277100,1779,1643,2356,107502,38720,1008,23,204.0,44.0,271
415,104070,Photo,1,3,4,7,0.0,49632,1110282,1653,1480,2567,1107833,48368,1513,7,227.0,15.0,249
442,98195,Photo,3,3,4,13,0.0,34480,191207,1591,1156,1926,184270,30720,1292,10,664.0,97.0,771
449,93684,Photo,1,2,6,13,1.0,27056,162816,2299,2127,2737,160270,25424,1146,6,234.0,26.0,266
460,92507,Photo,3,2,1,13,0.0,55520,665792,4544,3586,6624,648611,47488,3430,146,1546.0,181.0,1873

In [28]:
s1=df1[(df1['Type']=='Photo')&(df1['Paid']==1.0)][['Category','like','Paid']]
s1

     Category    like  Paid
3           2  1572.0   1.0
6           3   249.0   1.0
7           3   325.0   1.0
14          2   577.0   1.0
17          1   678.0   1.0
..        ...     ...   ...
467         2   200.0   1.0
473         3   136.0   1.0
475         3    65.0   1.0
476         1   579.0   1.0
491         3   105.0   1.0

[119 rows x 3 columns]

In [29]:
s2=df1[(df1['Type']=='Video')&(df1['Paid']==0.0)][['Category','like','Paid']]
s2

     Category   like  Paid
74          1   99.0   0.0
183         1  345.0   0.0
277         1  204.0   0.0

In [30]:
frames= [s1,s2]

answer=pd.concat(frames)
answer

     Category    like  Paid
3           2  1572.0   1.0
6           3   249.0   1.0
7           3   325.0   1.0
14          2   577.0   1.0
17          1   678.0   1.0
..        ...     ...   ...
476         1   579.0   1.0
491         3   105.0   1.0
74          1    99.0   0.0
183         1   345.0   0.0
277         1   204.0   0.0

[122 rows x 3 columns]

In [32]:
s3=df1[(df1['Post Month']==12)&(df1['Post Weekday']==7)][['comment','like']]
s3

    comment   like
7         0  325.0
8         0  161.0
21        0    0.0
22        0   16.0
23        0   72.0
37       16   76.0
38       11  227.0
39        1   44.0

In [33]:
s4=df1[(df1['Post Month']==12)&(df1['Post Weekday']==7)][['share','Total Interactions']]
s4

    share  Total Interactions
7    14.0                 339
8    31.0                 192
21    0.0                   0
22    2.0                  18
23   24.0                  96
37    8.0                 100
38   31.0                 269
39   14.0                  59

In [35]:
ans=pd.concat([s3,s4], axis=1)
ans

    comment   like  share  Total Interactions
7         0  325.0   14.0                 339
8         0  161.0   31.0                 192
21        0    0.0    0.0                   0
22        0   16.0    2.0                  18
23        0   72.0   24.0                  96
37       16   76.0    8.0                 100
38       11  227.0   31.0                 269
39        1   44.0   14.0                  59

In [36]:
transpose=df1.transpose()
transpose

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [37]:
t=df1.T
t

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [46]:
p1=pd.pivot_table(df1,index='Type', columns='Post Weekday', values='Total Interactions')
p1

Post Weekday,1,2,3,4,5,6,7
Type,,,,,,,
Link,74.000000,149.333333,81.500000,110.750000,71.750000,89.200000,12.000000
Photo,245.983871,204.931034,302.288462,267.333333,204.716981,158.343284,156.422535
Status,179.750000,51.000000,251.500000,324.750000,229.888889,256.375000,162.666667
Video,NaN,371.500000,261.500000,174.000000,550.000000,81.000000,NaN

In [45]:
pivot=df1.pivot_table(index='Type', columns='Post Weekday', values='Total Interactions')
pivot

Post Weekday,1,2,3,4,5,6,7
Type,,,,,,,
Link,74.000000,149.333333,81.500000,110.750000,71.750000,89.200000,12.000000
Photo,245.983871,204.931034,302.288462,267.333333,204.716981,158.343284,156.422535
Status,179.750000,51.000000,251.500000,324.750000,229.888889,256.375000,162.666667
Video,NaN,371.500000,261.500000,174.000000,550.000000,81.000000,NaN